# Generated by Django 4.0.3 on 2022-08-21 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_gender_profile_reg_token_and_more'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='profile2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='profiles',
            field=models.ManyToManyField(related_name='chatrooms', to='users.profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='messagetext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.messagetext'),
        ),
    ]
